name: unzip and upload
on:
  repository_dispatch:
    workflow_dispatch:
      inputs:
        path:
          description: '下载路径'
          required: true
          default: 'MyTelegram'

jobs:
  Onedriver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 'Create Config'
        run: |
          echo 'username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}' >> config.yml

      - name: Update system
        run: |
          sudo apt-get update

      - name: Check disk space before extraction
        run: |
          df -h

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true

      - name: Check disk space after extraction
        run: |
          df -h

      - name: 'Download file from PikPak'
        run: |
          chmod a+x pikpakcli
          ./pikpakcli download -p ${{ github.event.inputs.path }}
      - name: 安装7-Zip
        run: |
          sudo apt-get update
          sudo apt-get install p7zip-full -y


      - name: Extract 7zip file
        run: |
          7z x ${{ github.event.inputs.path }} -o. -r
        working-directory: ${{ github.workspace }}

      - name: Upload to gdcloud
        uses: wei/rclone@v1
        with:
          args: copy "${{ github.workspace }}/${{ github.event.inputs.path | replace: ".7z", "" }}" gdcloud:${{ secrets.cloudname }}

      - name: Upload to onedrive
        uses: wei/rclone@v1
        with:
          args: copy "${{ github.workspace }}/" onedrive:${{ github.event.inputs.path }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v1.2.3
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
