name: 谷歌云微软云单个3.yml
on:
  workflow_dispatch:
    inputs:
      path:
        description: '下载路径'
        required: true
        default: '二零二三年年十月二十五日三'

jobs:
  pikpak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Create Config'
        run: |
          echo 'username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}' >> config.yml
      - name: 更新
        run: |
           sudo apt-get update
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
           tool-cache: true
           android: true
           dotnet: true
           haskell: true
           large-packages: true
           docker-images: false
           swap-storage: true

      - name: 'Download file from PikPak'
        run: |
          chmod a+x pikpakcli
          ./pikpakcli download -c 5 -p ${{ github.event.inputs.path }} >/dev/null 2>&1

      - name: install Python3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install Python
        run: |
          python -m pip install --upgrade pip wheel
          pip install install requests
      - name: 下载加密程序
        run: |
          curl -L -o dist.tar.gz https://github.com/sdasdasddda/alist-encrypt/releases/download/0.0.1/dist.tar.gz
          tar -xzf dist.tar.gz

      - name: crypt file
        id: encrypt
        run: |
           ${{ github.workspace }}/dist/nodejs-linux '${{ secrets.ALIST_ENCRYPT_PASSWORD }}' aesctr enc '${{ github.workspace }}/${{ github.event.inputs.path }}' '${{ github.workspace }}/out/' >/dev/null 2>&1 encName
           filename=$(ls out | head -n1) >/dev/null 2>&1
           sha1_s=`openssl sha1 out/$filename | awk '{ print $2 }'` >/dev/null 2>&1
           header="OC-Checksum:sha1:$sha1_s" >/dev/null 2>&1
           echo "::set-output name=header::$header" >/dev/null 2>&1
           echo "::set-output name=filename::$filename" >/dev/null 2>&1
           echo "::set-output name=path::out/$filename" >/dev/null 2>&1
           size=$(ls -l out/$filename | awk '{print $5}' ) >/dev/null 2>&1
           echo "::set-output name=size::$size" >/dev/null 2>&1

      - name: Delete actions folder1
        run: |
         sudo rm -rf ${{ github.event.inputs.path }}/

      - name: upload onedrive
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy out/ cryptonedrive:/${{ github.event.inputs.path }}/ >/dev/null 2>&1

      - name: 上传gd
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy out/ cryptsajdshdjdgooglecloud:/${{ secrets.cloudname }}/${{ github.event.inputs.path }}/ >/dev/null 2>&1

      - name: 开启新的下载任务
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 谷歌云微软云单个4.yml
          ref: main
        
      - name: 删除旧的上传记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
